### PR TITLE
[NOJIRA] Add jsonOptions to types

### PR DESCRIPTION
**Pull request by jamesz96**
https://github.com/lux-group/svc-traveller/blob/master/src/api/tours/routes.ts#L20-L21

### CODE REVIEW

**Comment by semeer-acheerithodi-le** [comment]
value could be a number as well, right?
should be able to specify, let's say, limit in bytes, right?

**Review by semeer-acheerithodi-le — APPROVED** [review]

**Comment by jamesz96** [comment]
> value could be a number as well, right? should be able to specify, let's say, limit in bytes, right?

Looks like it can be `undefined` and `null` too
https://expressjs.com/en/api.html

**Comment by semeer-acheerithodi-le** [comment]
> > value could be a number as well, right? should be able to specify, let's say, limit in bytes, right?
> 
> Looks like it can be `undefined` and `null` too https://expressjs.com/en/api.html

nice

**Comment by nguyenchr** [comment]
could we just directly use the type from `@types/express`?

**Comment by jamesz96** [comment]
> could we just directly use the type from `@types/express`?

I don't think so :(

`bodyParser` is not exported through `express`

image

**Pull request merged**
