### PR TITLE
Allow json options to be passed per route

### PR DESCRIPTION
**Pull request by keithbro**
We want to be able to provide a size limit on the JSON payloads per endpoint.

This PR adds the JSON middleware to all handlers and allows options to be passed to it.

So you would do:

```
router.put({
  url: '/api/passport-details',
  jsonOptions: { limit: '20mb' },
  handler...
})
```

Also replaced uuid dependency with native crypto module and made Node 14 a requirement.

### CODE REVIEW

**Review by nguyenchr — APPROVED** [review]

**Comment by nguyenchr** [comment]
what's the advantage of replacing uuid out of curiosity? just removing an unneeded dependency ?

**Comment by keithbro** [comment]
> what's the advantage of replacing uuid out of curiosity? just removing an unneeded dependency ?

Yeah.. granted its not a big benefit. I do think its somewhat safer to be using in-built node libraries though instead of third party ones. Especially when you hear of these libraries having malicious code injected in to them and released to npm.

The other benefit is its an excuse to force people to upgrade their node version. I think the svc that needs this is actually on 12 :)

**Comment by nguyenchr** [comment]
> > what's the advantage of replacing uuid out of curiosity? just removing an unneeded dependency ?
> 
> Yeah.. granted its not a big benefit. I do think its somewhat safer to be using in-built node libraries though instead of third party ones. Especially when you hear of these libraries having malicious code injected in to them and released to npm.
> 
> The other benefit is its an excuse to force people to upgrade their node version. I think the svc that needs this is actually on 12 :)

Yep awesome, I think it's a good change BTW, was just curious

**Comment by J-Leg** [comment]
Worth adding the `jsonOptions` to the example in the `README` for the lazy peeps like me

**Comment by keithbro** [comment]
> Worth adding the `jsonOptions` to the example in the `README` for the lazy peeps like me

I already did add it to the README... do you mean in a different part of the readme? 🤔

**Comment by J-Leg** [comment]
> > Worth adding the `jsonOptions` to the example in the `README` for the lazy peeps like me
> 
> I already did add it to the README... do you mean in a different part of the readme? 🤔

Sorry, I must have missed it. Thx for adding it

**Pull request merged**
